### PR TITLE
#70 Add auto completion tab for fish, bash, zsh and powershell

### LINKED ISSUE #70: Menu Autocomplete
**Is your feature request related to a problem? Please describe.**
Feature Request

**Describe the solution you'd like**
Add the ability to tab/autocomplete the available commands for the builtin commands.

ex: **cybr-cli acc** becomes **cybr-cli accounts**

### PR DESCRIPTION
**Pull request by AndrewCopeland**
- Add auto completion to the CLI. Resolves #70

### CODE REVIEW

**Comment by infamousjoeg** [comment]
I'm testing this in `zsh` after install and it is not working.  Can you elaborate on how it functions?

I tested `cybr con[TAB]` and show `cybr version` as `cybr v0.1.1-beta`.

**Comment by AndrewCopeland** [comment]
Try out cybr completion --help for more info. You have to create a simple file in a specific location.

**Comment by infamousjoeg** [comment]
I think we should generate new docs and add instructions to the README in this PR before we merge.

I found that the copy pasta the CLI gave me needed to be adjusted as I had two different `zsh` locations in `$fpath[]`:

```shell
╰ echo $fpath[1]
/usr/local/Cellar/heroku/7.42.1/libexec/node_modules/@heroku-cli/plugin-autocomplete/autocomplete/zsh

╰ echo $fpath[2]
/Users/joegarcia/.zsh/completion

╰ cybr completion zsh > "${fpath[2]}/_cybr"
```

**Comment by AndrewCopeland** [comment]
README.md updated

**Review by infamousjoeg — APPROVED** [review]

**Pull request merged**
